### ISSUE TITLE
Log into site routers using serial to usb port on win/linux

### ISSUE THREAD

**Issue by CharlieTLe** [CharlieTLe/qurinet#1]
If Dinesh and Charlie were able to, so should Courtney and Yang. Comment below once you've completed the task. After everyone has completed the task, mark it as resolved.
- [x] Charlie
- [x] Courtney
- [x] Dinesh
- [x] Yang

**Comment by CharlieTLe** [comment]
I have finished this task.

**Comment by calaux** [comment]
I'm done with this.
